<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/05_String_Operations_Apply_Map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas using String Operations, Apply, Map

## String Operations in Pandas

String operations are used when a DataFrame column contains text/string data

* we use .str before string methods

str.upper()
str.lower()
str.title()
str.len()
str.contains()
str.startswith()
str.endswith()
str.replace()
str.strip()

In [1]:
## create the dataframe
import pandas as pd

df = pd.DataFrame({
    "Name": ["harish", "RAHUL", "sneha", "Kiran"],
    "City": ["hyderabad", "Delhi", "mumbai", "Bangalore"]
})

print(df)

     Name       City
0  harish  hyderabad
1   RAHUL      Delhi
2   sneha     mumbai
3   Kiran  Bangalore

In [3]:
df['Name'].str.upper()

0    HARISH
1     RAHUL
2     SNEHA
3     KIRAN
Name: Name, dtype: object

In [4]:
df['Name'].str.lower()

0    harish
1     rahul
2     sneha
3     kiran
Name: Name, dtype: object

In [7]:
df["City"].str.title()

0    Hyderabad
1        Delhi
2       Mumbai
3    Bangalore
Name: City, dtype: object

In [10]:
df["Name_Length"] = df["Name"].str.len()

df

     Name       City  Name_Length
0  harish  Hyderabad            6
1   RAHUL      Delhi            5
2   sneha     Mumbai            5
3   Kiran  Bangalore            5

In [11]:
df[df["Name"].str.contains("A")]

    Name   City  Name_Length
1  RAHUL  Delhi            5

In [13]:
df[df["Name"].str.startswith("h")]

     Name       City  Name_Length
0  harish  Hyderabad            6

In [14]:
df[df["Name"].str.endswith("L")]

    Name   City  Name_Length
1  RAHUL  Delhi            5

In [16]:
df["City"].str.replace("Delhi", "New Delhi")

0        Hyderabad
1    New New Delhi
2           Mumbai
3        Bangalore
Name: City, dtype: object

In [19]:
df["Name"].str.strip()

0    harish
1     RAHUL
2     sneha
3     Kiran
Name: Name, dtype: object

## Apply()


apply() is used to apply a function to values in a Series or across a DataFrame

In [20]:
df = pd.DataFrame({
    "Name": ["Harish", "Rahul", "Sneha"],
    "Marks": [85, 65, 92]
})

In [22]:
# suppose i need to add the 5 marks to the marks

def add_marks(x):
    return x + 5

df['new_marks']=df['Marks'].apply(add_marks)
df

     Name  Marks  new_marks
0  Harish     85         90
1   Rahul     65         70
2   Sneha     92         97

## Map()

map() is commonly used with a Series to transform or replace its values

In [25]:
df = pd.DataFrame({
    "Name": ["Harish", "Rahul", "Sneha"],
    "Gender": ["M", "M", "F"]
})
df

     Name Gender
0  Harish      M
1   Rahul      M
2   Sneha      F

In [26]:
df['Gender']=df['Gender'].map({'M':'Male','F':'Female'})

df

     Name  Gender
0  Harish    Male
1   Rahul    Male
2   Sneha  Female